# Generated by Django 2.1.1 on 2018-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('profilePicture', models.CharField(max_length=80)),
                ('aboutMeTitle', models.CharField(max_length=100)),
                ('aboutMeDescription', models.TextField(max_length=3000)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Curriculum Vitae',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('universityCollege', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.ManyToManyField(to='qwsite.Education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.ManyToManyField(to='qwsite.Experience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='hobbies',
            field=models.ManyToManyField(to='qwsite.Hobbies'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(to='qwsite.Skills'),
        ),
    ]
