# Generated by Django 2.1.1 on 2018-11-08 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwsite', '0007_auto_20181108_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-toDate',), 'verbose_name_plural': 'Experience'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.AddField(
            model_name='experience',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2018, 11, 8, 16, 59, 11, 464929)),
        ),
        migrations.AddField(
            model_name='experience',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2018, 11, 8, 16, 59, 11, 464929)),
        ),
    ]
