# Generated by Django 2.1.5 on 2019-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwsite', '0012_auto_20190211_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=4, verbose_name='month'),
        ),
    ]
