# Generated by Django 2.1.1 on 2018-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwsite', '0002_auto_20181108_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(),
        ),
    ]
