# Generated by Django 2.1.1 on 2018-11-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qwsite', '0006_auto_20181108_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-year',), 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('-year', '-month'), 'verbose_name_plural': 'Training'},
        ),
    ]
