# Generated by Django 2.1.1 on 2018-11-08 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwsite', '0008_auto_20181108_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fromDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='experience',
            name='toDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
